### ISSUE TITLE
Upgrade `@sinclair/typebox` to avoid TS error in 4.5+

### ISSUE THREAD

**Issue by rezonant** [rweich/streamdeck-ts#18] opened 2022-03-25 02:28 UTC
> node_modules/@rweich/streamdeck-events/node_modules/@sinclair/typebox/typebox.d.ts:224:104 - error TS2589: Type instantiation is excessively deep and possibly infinite.

https://github.com/sinclairzx81/typebox/issues/119#issuecomment-972757387

There are two different versions of typebox in the package tree, one should be new enough to avoid and one isn't:

```
> npm ls @sinclair/typebox
`-- @rweich/streamdeck-ts@4.0.0
  +-- @rweich/streamdeck-events@3.1.0
  | `-- @sinclair/typebox@0.17.8
  `-- @sinclair/typebox@0.23.4
```

**Comment by rweich** [comment] 2022-03-29 11:42
hey there,

thanks for reporting! 
I can't reproduce this error. Where/how do you get this?

**Comment by rweich** [comment] 2022-03-30 14:45
updated typebox in rweich/streamdeck-events#24

should be fixed - but i can't validate

**Closed by rweich** 2022-03-30 14:45 UTC
